package credit_agricole.ticket_automat;

public enum TicketType {
	DISPOSABLE_NORMAL,
	DISPOSABLE_SPECIAL,
	TEMPORAL_30_MIN,
	TEMPORAL_60_MIN,
	TEMPORAL_90_MIN,
	TEMPORAL_24_H,
	
	DISPOSABLE_NORMAL_REDUCED,
	DISPOSABLE_SPECIAL_REDUCED,
	TEMPORAL_30_MIN_REDUCED,
	TEMPORAL_60_MIN_REDUCED,
	TEMPORAL_90_MIN_REDUCED,
	TEMPORAL_24_H_REDUCED;
}
